In [127]:
import os
from pathlib import Path
import pandas as pd
df = pd.read_csv("dataset.csv", low_memory=False)

In [128]:
print(df.shape)

(692703, 85)


In [129]:
print(df.head(5))

                                  Flow ID      Source IP   Source Port  \
0  192.168.10.14-209.48.71.168-49459-80-6  192.168.10.14         49459   
1  192.168.10.3-192.168.10.17-389-49453-6  192.168.10.17         49453   
2   192.168.10.3-192.168.10.17-88-46124-6  192.168.10.17         46124   
3  192.168.10.3-192.168.10.17-389-49454-6  192.168.10.17         49454   
4   192.168.10.3-192.168.10.17-88-46126-6  192.168.10.17         46126   

   Destination IP   Destination Port   Protocol      Timestamp  \
0   209.48.71.168                 80          6  5/7/2017 8:42   
1    192.168.10.3                389          6  5/7/2017 8:42   
2    192.168.10.3                 88          6  5/7/2017 8:42   
3    192.168.10.3                389          6  5/7/2017 8:42   
4    192.168.10.3                 88          6  5/7/2017 8:42   

    Flow Duration   Total Fwd Packets   Total Backward Packets   ...    \
0           38308                   1                        1   ...     
1         

In [130]:
print(list(df.columns.values))

['Flow ID', ' Source IP', ' Source Port', ' Destination IP', ' Destination Port', ' Protocol', ' Timestamp', ' Flow Duration', ' Total Fwd Packets', ' Total Backward Packets', 'Total Length of Fwd Packets', ' Total Length of Bwd Packets', ' Fwd Packet Length Max', ' Fwd Packet Length Min', ' Fwd Packet Length Mean', ' Fwd Packet Length Std', 'Bwd Packet Length Max', ' Bwd Packet Length Min', ' Bwd Packet Length Mean', ' Bwd Packet Length Std', 'Flow Bytes/s', ' Flow Packets/s', ' Flow IAT Mean', ' Flow IAT Std', ' Flow IAT Max', ' Flow IAT Min', 'Fwd IAT Total', ' Fwd IAT Mean', ' Fwd IAT Std', ' Fwd IAT Max', ' Fwd IAT Min', 'Bwd IAT Total', ' Bwd IAT Mean', ' Bwd IAT Std', ' Bwd IAT Max', ' Bwd IAT Min', 'Fwd PSH Flags', ' Bwd PSH Flags', ' Fwd URG Flags', ' Bwd URG Flags', ' Fwd Header Length', ' Bwd Header Length', 'Fwd Packets/s', ' Bwd Packets/s', ' Min Packet Length', ' Max Packet Length', ' Packet Length Mean', ' Packet Length Std', ' Packet Length Variance', 'FIN Flag Count', 

In [131]:
for column_name in df.columns:
    if df[column_name].dtypes=='object':
        a=df[column_name].unique()
        a= len(a)
        print(column_name+" has "+str(a)+" unique values.")

Flow ID has 226768 unique values.
 Source IP has 7689 unique values.
 Destination IP has 9012 unique values.
 Timestamp has 509 unique values.
Flow Bytes/s has 450842 unique values.
 Flow Packets/s has 387031 unique values.
 Label has 6 unique values.


In [132]:
y = df[" Label"]
X = df.drop(["Flow ID"," Label", " Source IP"," Destination IP", " Timestamp", "Flow Bytes/s"," Flow Packets/s" ],1)

print(X.head(5))
print(y.head(5))


    Source Port   Destination Port   Protocol   Flow Duration  \
0         49459                 80          6           38308   
1         49453                389          6             479   
2         46124                 88          6            1095   
3         49454                389          6           15206   
4         46126                 88          6            1092   

    Total Fwd Packets   Total Backward Packets  Total Length of Fwd Packets  \
0                   1                        1                            6   
1                  11                        5                          172   
2                  10                        6                         3150   
3                  17                       12                         3452   
4                   9                        6                         3150   

    Total Length of Bwd Packets   Fwd Packet Length Max  \
0                           6.0                       6   
1               

In [133]:
#Encode target values and convert to one hot encoding.
import numpy as np
from keras.utils import np_utils
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()
encoder.fit(y)
encoded_y = encoder.transform(y)
dummy_y = np_utils.to_categorical(encoded_y)

In [134]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.25, random_state=1)

In [135]:
print(y_train.shape)
print(X_train.shape)
print(y_test.shape)
print(X_test.shape)

(519527,)
(519527, 78)
(173176,)
(173176, 78)


In [136]:
print(X_train.head(5))

         Source Port   Destination Port   Protocol   Flow Duration  \
451289         56043                443          6          181103   
107684         50328                 80          6            2368   
62920          16182                443          6       116324083   
382089         51866                 53         17           80427   
192370         52072                 80          6        85638973   

         Total Fwd Packets   Total Backward Packets  \
451289                   7                        5   
107684                   3                        4   
62920                  141                      193   
382089                   4                        2   
192370                   8                        5   

        Total Length of Fwd Packets   Total Length of Bwd Packets  \
451289                          376                        3508.0   
107684                          311                       11595.0   
62920                          3134      

In [137]:
from sklearn.linear_model import SGDClassifier
sgd_clf = SGDClassifier(random_state=42)
#sgd_clf.fit(train_features, train_target)
sgd_clf.fit(X_train, y_train)

C:\Users\Amish\AppData\Local\Enthought\Canopy\edm\envs\User\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:128: FutureWarning: max_iter and tol parameters have been added in <class 'sklearn.linear_model.stochastic_gradient.SGDClassifier'> in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  "and default tol will be 1e-3." % type(self), FutureWarning)


SGDClassifier(alpha=0.0001, average=False, class_weight=None, epsilon=0.1,
       eta0=0.0, fit_intercept=True, l1_ratio=0.15,
       learning_rate='optimal', loss='hinge', max_iter=None, n_iter=None,
       n_jobs=1, penalty='l2', power_t=0.5, random_state=42, shuffle=True,
       tol=None, verbose=0, warm_start=False)

In [138]:
sgd_clf.predict(X_train)


array(['DoS Hulk', 'DoS Hulk', 'BENIGN', ..., 'BENIGN', 'BENIGN',
       'DoS Hulk'],
      dtype='<U16')

In [143]:
from sklearn.model_selection import cross_val_score
print("CROSS VAL SCORE: ")
print(cross_val_score(sgd_clf, X_train, y_train,  scoring="accuracy"))

from sklearn.model_selection import cross_val_predict
y_train_pred = cross_val_predict(sgd_clf, X_train, y_train, cv=3)

from sklearn.metrics import confusion_matrix
print("CONFUSION MATRIX: ")
print(confusion_matrix(y_train, y_train_pred))

#Micro for average of all classes.

from sklearn.metrics import precision_score, recall_score
print("Precision Score: ")
print(precision_score(y_train, y_train_pred, average='micro'))
print("Recall Score: ")
print(recall_score(y_train, y_train_pred, average='micro')) 

from sklearn.metrics import f1_score
print("f1 score: ")
print(f1_score(y_train, y_train_pred, average='micro'))
y_scores = cross_val_predict(sgd_clf, X_train, y_train, cv=3, method="decision_function")

CROSS VAL SCORE: 


C:\Users\Amish\AppData\Local\Enthought\Canopy\edm\envs\User\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:128: FutureWarning: max_iter and tol parameters have been added in <class 'sklearn.linear_model.stochastic_gradient.SGDClassifier'> in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  "and default tol will be 1e-3." % type(self), FutureWarning)
C:\Users\Amish\AppData\Local\Enthought\Canopy\edm\envs\User\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:128: FutureWarning: max_iter and tol parameters have been added in <class 'sklearn.linear_model.stochastic_gradient.SGDClassifier'> in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  "and default tol will b

[ 0.8644335   0.84665978  0.86215519]


C:\Users\Amish\AppData\Local\Enthought\Canopy\edm\envs\User\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:128: FutureWarning: max_iter and tol parameters have been added in <class 'sklearn.linear_model.stochastic_gradient.SGDClassifier'> in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  "and default tol will be 1e-3." % type(self), FutureWarning)
C:\Users\Amish\AppData\Local\Enthought\Canopy\edm\envs\User\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:128: FutureWarning: max_iter and tol parameters have been added in <class 'sklearn.linear_model.stochastic_gradient.SGDClassifier'> in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  "and default tol will b

CONFUSION MATRIX: 
[[291201   4064  28780    892   2773   2026]
 [  1820   5830     24     28      7      0]
 [ 29239     72 144221      5     45      0]
 [   602     48    430   2812    218      0]
 [  2546      1    166    109   1560      0]
 [     8      0      0      0      0      0]]
Precision Score: 
0.857749452868
Recall Score: 
0.857749452868
f1 score: 
0.857749452868


C:\Users\Amish\AppData\Local\Enthought\Canopy\edm\envs\User\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:128: FutureWarning: max_iter and tol parameters have been added in <class 'sklearn.linear_model.stochastic_gradient.SGDClassifier'> in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  "and default tol will be 1e-3." % type(self), FutureWarning)
C:\Users\Amish\AppData\Local\Enthought\Canopy\edm\envs\User\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:128: FutureWarning: max_iter and tol parameters have been added in <class 'sklearn.linear_model.stochastic_gradient.SGDClassifier'> in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  "and default tol will b

In [148]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(random_state=42)
rfc.fit(X_train, y_train)
rfc.predict(X_test)
print(cross_val_score(rfc, X_train, y_train, cv=3, scoring="accuracy"))
y_probas_forest = cross_val_predict(rfc, X_train, y_train, cv=3, method="predict_proba")



y_train_pred = cross_val_predict(rfc, X_train, y_train, cv=3)
print("CONFUSION MATRIX: ")
print(confusion_matrix(y_train, y_train_pred))
print("PRECISION SCORE: ")
print(precision_score(y_train, y_train_pred ,average='micro'))
print("RECALL SCORE: ")
print(recall_score(y_train, y_train_pred, average='micro')) 
print("F1 score: ")
print(f1_score(y_train, y_train_pred,average='micro'))


[ 0.99921468  0.99937059  0.9992724 ]
CONFUSION MATRIX: 
[[329586      3    135      8      4      0]
 [    16   7680     10      3      0      0]
 [   118     14 173450      0      0      0]
 [    17      4      0   4075     14      0]
 [    18      1      1      4   4358      0]
 [     1      0      0      0      0      7]]
PRECISION SCORE: 
0.999285888895
RECALL SCORE: 
0.999285888895
F1 score: 
0.999285888895


In [149]:
from sklearn.preprocessing import StandardScaler
StdSc= StandardScaler()

X_scaled= StdSc.fit_transform(X_train)
sgd_scaled = SGDClassifier(random_state=42)
sgd_scaled.fit(X_scaled, y_train)

C:\Users\Amish\AppData\Local\Enthought\Canopy\edm\envs\User\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:128: FutureWarning: max_iter and tol parameters have been added in <class 'sklearn.linear_model.stochastic_gradient.SGDClassifier'> in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  "and default tol will be 1e-3." % type(self), FutureWarning)


SGDClassifier(alpha=0.0001, average=False, class_weight=None, epsilon=0.1,
       eta0=0.0, fit_intercept=True, l1_ratio=0.15,
       learning_rate='optimal', loss='hinge', max_iter=None, n_iter=None,
       n_jobs=1, penalty='l2', power_t=0.5, random_state=42, shuffle=True,
       tol=None, verbose=0, warm_start=False)

In [150]:
y_scores = cross_val_predict(sgd_scaled, X_scaled, y_train, cv=3, method="decision_function")

C:\Users\Amish\AppData\Local\Enthought\Canopy\edm\envs\User\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:128: FutureWarning: max_iter and tol parameters have been added in <class 'sklearn.linear_model.stochastic_gradient.SGDClassifier'> in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  "and default tol will be 1e-3." % type(self), FutureWarning)
C:\Users\Amish\AppData\Local\Enthought\Canopy\edm\envs\User\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:128: FutureWarning: max_iter and tol parameters have been added in <class 'sklearn.linear_model.stochastic_gradient.SGDClassifier'> in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  "and default tol will b

In [151]:
sgd_scaled.predict(X_scaled)

array(['BENIGN', 'DoS Hulk', 'BENIGN', ..., 'BENIGN', 'BENIGN', 'DoS Hulk'],
      dtype='<U16')

In [152]:
print(cross_val_score(sgd_scaled, X_scaled, y_train, cv=3, scoring="accuracy"))

from sklearn.model_selection import cross_val_predict
y_train_pred = cross_val_predict(sgd_scaled, X_scaled, y_train, cv=3)

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_train, y_train_pred))

from sklearn.metrics import precision_score, recall_score
print(precision_score(y_train, y_train_pred, average='micro'))
print(recall_score(y_train, y_train_pred, average='micro')) 

from sklearn.metrics import f1_score
print(f1_score(y_train, y_train_pred, average='micro'))
y_scores = cross_val_predict(sgd_scaled, X_scaled, y_train, cv=3, method="decision_function")

C:\Users\Amish\AppData\Local\Enthought\Canopy\edm\envs\User\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:128: FutureWarning: max_iter and tol parameters have been added in <class 'sklearn.linear_model.stochastic_gradient.SGDClassifier'> in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  "and default tol will be 1e-3." % type(self), FutureWarning)
C:\Users\Amish\AppData\Local\Enthought\Canopy\edm\envs\User\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:128: FutureWarning: max_iter and tol parameters have been added in <class 'sklearn.linear_model.stochastic_gradient.SGDClassifier'> in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  "and default tol will b

[ 0.97856528  0.97928131  0.97688439]


C:\Users\Amish\AppData\Local\Enthought\Canopy\edm\envs\User\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:128: FutureWarning: max_iter and tol parameters have been added in <class 'sklearn.linear_model.stochastic_gradient.SGDClassifier'> in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  "and default tol will be 1e-3." % type(self), FutureWarning)
C:\Users\Amish\AppData\Local\Enthought\Canopy\edm\envs\User\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:128: FutureWarning: max_iter and tol parameters have been added in <class 'sklearn.linear_model.stochastic_gradient.SGDClassifier'> in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  "and default tol will b

[[324097    204   5011    259    165      0]
 [  1494   5999    210      4      2      0]
 [  1760    124 171698      0      0      0]
 [   790     10    211   3072     27      0]
 [   807    106      9    102   3358      0]
 [     8      0      0      0      0      0]]
0.978243671647
0.978243671647
0.978243671647


C:\Users\Amish\AppData\Local\Enthought\Canopy\edm\envs\User\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:128: FutureWarning: max_iter and tol parameters have been added in <class 'sklearn.linear_model.stochastic_gradient.SGDClassifier'> in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  "and default tol will be 1e-3." % type(self), FutureWarning)
C:\Users\Amish\AppData\Local\Enthought\Canopy\edm\envs\User\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:128: FutureWarning: max_iter and tol parameters have been added in <class 'sklearn.linear_model.stochastic_gradient.SGDClassifier'> in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  "and default tol will b

In [153]:
from sklearn.pipeline import Pipeline
#from sklearn.preprocessing import StandardScaler
from sklearn.svm import LinearSVC
svm_clf = Pipeline([
("scaler", StandardScaler()),
("linear_svc", LinearSVC(C=1, loss="hinge")),
])

svm_clf.fit(X_train, y_train)

#svm_clf.predict(X_train)
prediction = svm_clf.predict(X_train)
svm_clf.score(X_train, y_train)

0.99256823995672983

In [154]:
svm_clf.score(X_test, y_test)

0.99281655656672985

In [155]:
from sklearn.neighbors import KNeighborsClassifier 
knn = KNeighborsClassifier(n_neighbors = 6).fit(X_scaled, y_train)


In [156]:
knn_predictions = knn.predict(X_test)  
cm = confusion_matrix(y_test, knn_predictions) 
print(knn_predictions)
print(cm)

['BENIGN' 'BENIGN' 'BENIGN' ..., 'BENIGN' 'BENIGN' 'BENIGN']
[[98556  1105 10634     0     0     0]
 [ 1662   601   321     0     0     0]
 [19105     1 38385     0     0     0]
 [ 1233    46   110     0     0     0]
 [ 1378     3    33     0     0     0]
 [    3     0     0     0     0     0]]


In [157]:
from sklearn.naive_bayes import GaussianNB 
gnb = GaussianNB().fit(X_train, y_train) 
gnb_predictions = gnb.predict(X_test) 
  
# accuracy on X_test 
accuracy = gnb.score(X_test, y_test) 
print (accuracy) 
  
# creating a confusion matrix 
cm = confusion_matrix(y_test, gnb_predictions) 
print(cm)

0.50981082829
[[28628  7848 65247  2792  5779     1]
 [    1  2317   145    27    94     0]
 [   85  1722 55547    24   113     0]
 [   53   161   106  1019    50     0]
 [    9   386   211    35   773     0]
 [    0     0     0     0     0     3]]
